//
//  Countries.swift
//  Autocomplete
//
//  Created by Amir Rezvani on 3/6/16.
//  Copyright © 2016 cjcoaxapps. All rights reserved.
//

let countries = ["African Union",
    "Andorra",
    "Armenia",
    "Austria",
    "Bahamas",
    "Barbados",
    "Belarus",
    "Belgium",
    "Benin",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Bulgaria",
    "Burkina Faso",
    "Cameroon",
    "Canada",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Congo",
    "Czech Republic",
    "Denmark",
    "Egypt",
    "England",
    "Estonia",
    "Finland",
    "Flag Of Europe",
    "France",
    "Gabon",
    "Germany",
    "Great Britain",
    "Hungary",
    "Iceland",
    "Iran",
    "Ireland",
    "Italy",
    "Jamaica",
    "Kuwait",
    "Latvia",
    "Liberia",
    "Lithuania",
    "Macedonia",
    "Mali",
    "Netherlands",
    "New Zealand",
    "Norway",
    "Philippines",
    "Poland",
    "Portugal",
    "Romania",
    "Russian Federation",
    "Slovakia",
    "Slovenia",
    "Spain",
    "Sweden",
    "Switzerland",
    "Togo",
    "Turkey",
    "Ukraine",
    "USA",
    "Wales"]